name: Python Tests

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  tsql-test:
    runs-on: ubuntu-latest

    steps:
      - name: Run ms-sql container
        run: |
          docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=StrongPword8' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Tests
        run: python -m unittest 02_cnn_np_ops/test.py

  make-pr:
    needs: [plsql-test, tsql-test, plpgsql-test, mysql-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        if: github.actor == 'ThugPigeon653'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto PR
          title: Automated PR
          body: Created by a development branch
          branch: main
        if: github.actor == 'ThugPigeon653'
          
      - name: Merge Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Merge PR
          title: Merge Pull Request
          body: This PR was automatically merged.
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.actor == 'ThugPigeon653'

      - name: Delete Branch
        run: |
          git push --delete origin ${{ github.ref }}
        if: success() && github.actor == 'ThugPigeon653'