name: testQL Tests
on:
  push:
    branches:
    - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup py installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install numpy

    - name: tests
      run: |
            cd 02_cnn_np_ops
            python -m unittest test_02.py

  make-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        if: github.actor == 'ThugPigeon653'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto PR
          title: Automated PR
          body: Created by a development branch
          branch: main
        if: github.actor == 'ThugPigeon653'
          
      - name: Merge Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Merge PR
          title: Merge Pull Request
          body: This PR was automatically merged.
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.actor == 'ThugPigeon653'